### ISSUE TITLE
Typescript errors on import

### ISSUE THREAD

**Issue by nick-allen** [coinbase/gdax-tt#41]
gdax-tt v0.1.16
node v8.3.0
typescript 2.5.3

Trying to follow along with the getting started guide. Trying to compile file with GTT import leads to following failure

```typescript
import * as GTT from "gdax-trading-toolkit";
...
```

```
node_modules/gdax-trading-toolkit/build/src/core/HFTFilter.d.ts(22,22): error TS2415: Class 'HFTFilter' incorrectly extends base class 'Duplex'.
  Property '_write' is protected in type 'HFTFilter' but public in type 'Duplex'.
node_modules/gdax-trading-toolkit/build/src/core/LiveOrderbook.d.ts(39,22): error TS2415: Class 'LiveOrderbook' incorrectly extends base class 'Duplex'.
  Property '_write' is protected in type 'LiveOrderbook' but public in type 'Duplex'.
node_modules/gdax-trading-toolkit/build/src/core/MessageQueue.d.ts(67,22): error TS2415: Class 'MessageQueue' incorrectly extends base class 'Duplex'.
  Property '_write' is protected in type 'MessageQueue' but public in type 'Duplex'.
node_modules/gdax-trading-toolkit/build/src/core/RateLimiter.d.ts(21,22): error TS2415: Class 'RateLimiter' incorrectly extends base class 'Transform'.
  Property '_transform' is protected in type 'RateLimiter' but public in type 'Transform'.
node_modules/gdax-trading-toolkit/build/src/core/Trader.d.ts(46,22): error TS2415: Class 'Trader' incorrectly extends base class 'Writable'.
  Property '_write' is protected in type 'Trader' but public in type 'Writable'.
node_modules/gdax-trading-toolkit/build/src/exchanges/ExchangeFeed.d.ts(28,31): error TS2415: Class 'ExchangeFeed' incorrectly extends base class 'Readable'.
  Property '_read' is protected in type 'ExchangeFeed' but public in type 'Readable'.
node_modules/gdax-trading-toolkit/build/src/lib/StaticCommandSet.d.ts(20,22): error TS2415: Class 'StaticCommandSet' incorrectly extends base class 'Readable'.
  Property '_read' is protected in type 'StaticCommandSet' but public in type 'Readable'.
node_modules/gdax-trading-toolkit/build/src/utils/index.d.ts(3,29): error TS7016: Could not find a declaration file for module 'pushbullet'. '/app/node_modules/pushbullet/index.js' implicitly has an 'any' type.
```

**Comment by CjS77** [comment]
That sucks.

I've been developing using TS 2.4.x and Node 7.x., 
but thanks for flagging, this will need to be addressed.

**Comment by CjS77** [comment]
@nick-allen Using the npm package from another project (and just copying the tutorials over),  I can't reproduce this error exactly, I'm afraid. Using v0.1.17, I did get some "type definition not found" errors, but copying the `types` folder from the repo resolved those too (this is less than ideal, I'll admit -- TS should find them in the repo folder, but I don't have time to look at that right now). 

Now running `ts-node tutorials/t001_feeds.ts` works:

``` 
2017-10-05T11:26:45.673Z - info: Creating new Websocket connection to wss://ws-feed.gdax.com 
2017-10-05T11:26:45.693Z - debug: Reconnecting to wss://ws-feed.gdax.com  in 0 seconds...
2017-10-05T11:26:45.693Z - debug: Closing existing socket prior to reconnecting to wss://ws-feed.gdax.com
2017-10-05T11:26:47.036Z - debug: Connection to wss://ws-feed.gdax.com  has been established.
2017-10-05T11:26:47.036Z - debug: Sending {"type":"subscribe","product_ids":["BTC-USD","ETH-USD","LTC-USD"],"channels":["level2","matches","ticker","user","heartbeat"]} message to WS server
2017-10-05T11:26:48.588Z - debug: GDAX Feed subscriptions confirmed type=subscriptions, channels=[name=level2, product_ids=[BTC-USD, ETH-USD, LTC-USD], name=matches, product_ids=[BTC-USD, ETH-USD, LTC-USD], name=ticker, product_ids=[BTC-USD, ETH-USD, LTC-USD], name=user, product_ids=[BTC-USD, ETH-USD, LTC-USD], name=heartbeat, product_ids=[BTC-USD, ETH-USD, LTC-USD]]
1000 messages received
BTC-USD: level: 451     snapshot: 1     ticker: 3       trade: 2        unknown: 1
ETH-USD: level: 269     snapshot: 1     ticker: 2       trade: 1        unknown: 1
LTC-USD: level: 263     snapshot: 1     ticker: 2       trade: 1        unknown: 1
```
Here are some config options 
```
$ ts-node -v
ts-node v3.3.0
node v8.6.0           # Also worked with v7.x.y
typescript v2.5.3   # Also worked with 2.4.x
```
tsconfig.jon:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "lib": ["es6", "es2016", "ES2016.Array.Include", "dom", "ES2017.object"],
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strictNullChecks": false,
    "experimentalDecorators": true,
    "outDir": "build",
    "sourceMap": true,
    "allowJs": true
  },
  "include": [
    "tutorials/**/*.ts",
    "types/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Let me know if any of this helps

**Comment by oatssss** [comment]
"gdax-trading-toolkit": "0.2.1"
node v8.9.3
tsc 2.6.2

I get the following errors when transpiling [`tutorials/t001_feeds.ts`](https://github.com/coinbase/gdax-tt/blob/master/tutorials/t001_feeds.ts):

```
node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts(14,23): error TS7016: Could not find a declaration file for module 'ccxt'. '/Developer/Repos/gdax-bot/node_modules/ccxt/ccxt.js' implicitly has an 'any' type.
  Try `npm install @types/ccxt` if it exists or add a new declaration (.d.ts) file containing `declare module 'ccxt';`
node_modules/gdax-trading-toolkit/build/src/exchanges/ccxt/index.d.ts(15,39): error TS7016: Could not find a declaration file for module 'ccxt'. '/Developer/Repos/gdax-bot/node_modules/ccxt/ccxt.js' implicitly has an 'any' type.
  Try `npm install @types/ccxt` if it exists or add a new declaration (.d.ts) file containing `declare module 'ccxt';`
node_modules/gdax/index.d.ts(2,32): error TS7006: Parameter 'err' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(2,37): error TS7006: Parameter 'response' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(138,9): error TS7010: 'getProducts', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(141,9): error TS7010: 'getProductOrderBook', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(144,9): error TS7010: 'getProductTicker', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(147,9): error TS7010: 'getProductTrades', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(150,9): error TS7010: 'getProductTradeStream', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(153,9): error TS7010: 'getProductHistoricRates', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(156,9): error TS7010: 'getProduct24HrStats', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(159,9): error TS7010: 'getCurrencies', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(162,9): error TS7010: 'getTime', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(169,9): error TS7010: 'getCoinbaseAccounts', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(172,9): error TS7010: 'getAccounts', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(175,9): error TS7010: 'getAccount', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(178,9): error TS7010: 'getAccountHistory', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(181,9): error TS7010: 'getAccountHistory', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(184,9): error TS7010: 'getAccountHolds', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(187,9): error TS7010: 'getAccountHolds', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(190,9): error TS7010: 'buy', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(193,9): error TS7010: 'sell', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(196,9): error TS7010: 'cancelOrder', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(196,21): error TS7006: Parameter 'orderID' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(197,21): error TS7006: Parameter 'orderID' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(199,9): error TS7010: 'cancelAllOrders', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(202,9): error TS7010: 'getOrders', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(205,9): error TS7010: 'getOrders', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(208,9): error TS7010: 'getOrder', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(208,18): error TS7006: Parameter 'orderID' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(209,18): error TS7006: Parameter 'orderID' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(211,9): error TS7010: 'getFills', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(214,9): error TS7010: 'getFills', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(217,9): error TS7010: 'getFundings', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(217,21): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(218,21): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(220,9): error TS7010: 'repay', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(220,15): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(221,15): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(223,9): error TS7010: 'marginTransfer', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(223,24): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(224,24): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(226,9): error TS7010: 'closePosition', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(226,23): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(227,23): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(229,9): error TS7010: 'deposit', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(229,17): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(230,17): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(232,9): error TS7010: 'withdraw', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(232,18): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(233,18): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(235,9): error TS7010: 'withdrawCrypto', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(235,24): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(236,24): error TS7006: Parameter 'params' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(238,9): error TS7010: 'getTrailingVolume', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(245,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(245,45): error TS7006: Parameter 'data' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(246,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(246,43): error TS7006: Parameter 'err' implicitly has an 'any' type.
node_modules/gdax/index.d.ts(247,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/gdax/index.d.ts(248,9): error TS7010: 'on', which lacks return-type annotation, implicitly has an 'any' return type.
```

All errors disappear if I comment out `"noImplicitAny": true` in `tsconfig.json`.

**Comment by mbana** [comment]
Used fix as mentioned here: https://github.com/coinbase/gdax-tt/issues/41#issuecomment-351349812.

The `package.json` in the instructions needs updating 'cause it says to set `"noImplicitAny": true` which causes compile errors with the version of `TypeScript` listed in the `package.json`.

Would be nice to have a demo app that included the library and did something really basic as a reference point.

Thanks,
